using System.ComponentModel.DataAnnotations;

namespace SleazyRetailers.Models
{
    public class Order
    {
        public string Id { get; set; } // No [Required] attribute - generated by Azure

        public string CustomerId { get; set; } // Set by controller, not user

        [Required(ErrorMessage = "Please select a product")]
        [Display(Name = "Product")]
        public string ProductId { get; set; }

        [Required(ErrorMessage = "Quantity is required")]
        [Range(1, int.MaxValue, ErrorMessage = "Quantity must be at least 1")]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "Shipping address is required")]
        [Display(Name = "Shipping Address")]
        public string ShippingAddress { get; set; }

        public string Status { get; set; } // Set by controller

        public DateTime OrderDate { get; set; } // Set by controller

        public decimal TotalAmount { get; set; } // Calculated by controller
    }
}