using Microsoft.AspNetCore.Mvc;
using SleazyRetailers.Models;
using SleazyRetailers.Services;

namespace SleazyRetailers.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAzureStorageService _azureStorageService;

        public OrderController(IAzureStorageService azureStorageService)
        {
            _azureStorageService = azureStorageService;
        }

        // GET: /Order/Index (Admin only - manage all orders)
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("Role") != "Admin")
                return RedirectToAction("Login", "Account");

            try
            {
                var orders = await _azureStorageService.GetOrdersAsync();
                return View(orders);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error loading orders: {ex.Message}";
                return View(new List<Order>());
            }
        }

        // GET: /Order/Create (Customer creates order)
        public async Task<IActionResult> Create()
        {
            if (HttpContext.Session.GetString("Role") != "Customer")
                return RedirectToAction("Login", "Account");

            try
            {
                // Get products for customer to choose from
                var products = await _azureStorageService.GetProductsAsync();

                if (!products.Any())
                {
                    TempData["ErrorMessage"] = "No products available. Please ask administrator to add products first.";
                    return RedirectToAction("Dashboard", "Customer");
                }

                ViewBag.Products = products;
                return View();
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error loading products: " + ex.Message;
                return RedirectToAction("Dashboard", "Customer");
            }
        }

        // POST: /Order/Create (Customer creates order)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Order order)
        {
            if (HttpContext.Session.GetString("Role") != "Customer")
                return RedirectToAction("Login", "Account");

            try
            {
                Console.WriteLine($"=== ORDER CREATION STARTED ===");

                // Remove ModelState errors for ALL fields that are set by the system
                ModelState.Remove("Id");
                ModelState.Remove("CustomerId");
                ModelState.Remove("Status");
                ModelState.Remove("OrderDate");
                ModelState.Remove("TotalAmount");

                // Set system values (these are not set by the user form)
                order.Id = null; // Will be generated by Azure Storage
                order.CustomerId = HttpContext.Session.GetString("UserId");
                order.Status = "Pending";
                order.OrderDate = DateTime.Now;

                Console.WriteLine($"Customer ID from session: {order.CustomerId}");
                Console.WriteLine($"Product ID from form: {order.ProductId}");
                Console.WriteLine($"Quantity from form: {order.Quantity}");
                Console.WriteLine($"Shipping Address from form: {order.ShippingAddress}");

                if (ModelState.IsValid)
                {
                    Console.WriteLine("ModelState is valid - proceeding with order creation");

                    // Get the selected product to calculate total amount
                    var product = await _azureStorageService.GetProductByIdAsync(order.ProductId);
                    Console.WriteLine($"Product found: {product != null}");

                    if (product == null)
                    {
                        Console.WriteLine("ERROR: Product not found!");
                        ModelState.AddModelError("ProductId", "Selected product not found");
                        var products = await _azureStorageService.GetProductsAsync();
                        ViewBag.Products = products;
                        return View(order);
                    }

                    Console.WriteLine($"Product details - Name: {product.ProductName}, Price: {product.Price}, Stock: {product.StockAvailable}");

                    // Check if enough stock is available
                    if (product.StockAvailable < order.Quantity)
                    {
                        Console.WriteLine($"ERROR: Insufficient stock. Requested: {order.Quantity}, Available: {product.StockAvailable}");
                        ModelState.AddModelError("Quantity", $"Only {product.StockAvailable} items available in stock");
                        var products = await _azureStorageService.GetProductsAsync();
                        ViewBag.Products = products;
                        return View(order);
                    }

                    // Calculate and set total amount
                    order.TotalAmount = (decimal)(product.Price * order.Quantity);

                    Console.WriteLine($"Final order details:");
                    Console.WriteLine($"- CustomerId: {order.CustomerId}");
                    Console.WriteLine($"- ProductId: {order.ProductId}");
                    Console.WriteLine($"- Quantity: {order.Quantity}");
                    Console.WriteLine($"- TotalAmount: {order.TotalAmount}");
                    Console.WriteLine($"- Status: {order.Status}");
                    Console.WriteLine($"- ShippingAddress: {order.ShippingAddress}");

                    // Create the order
                    Console.WriteLine("Calling AddOrderAsync...");
                    await _azureStorageService.AddOrderAsync(order);
                    Console.WriteLine("Order successfully added to storage");

                    // Update product stock
                    Console.WriteLine("Updating product stock...");
                    product.StockAvailable -= order.Quantity;
                    await _azureStorageService.UpdateProductAsync(product, null);
                    Console.WriteLine("Product stock updated");

                    TempData["SuccessMessage"] = $"Order placed successfully! Order Total: ${order.TotalAmount}. Your order is now pending.";
                    Console.WriteLine("=== ORDER CREATION COMPLETED SUCCESSFULLY ===");
                    return RedirectToAction("MyOrders", "Customer");
                }
                else
                {
                    Console.WriteLine("ModelState is INVALID");
                    foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                    {
                        Console.WriteLine($"Validation error: {error.ErrorMessage}");
                    }
                    Console.WriteLine("ModelState errors count: " + ModelState.ErrorCount);
                }

                // If model state is invalid, reload products and return to view
                var reloadProducts = await _azureStorageService.GetProductsAsync();
                ViewBag.Products = reloadProducts;
                return View(order);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"=== ORDER CREATION FAILED WITH EXCEPTION ===");
                Console.WriteLine($"Error: {ex.Message}");
                Console.WriteLine($"Stack trace: {ex.StackTrace}");
                if (ex.InnerException != null)
                {
                    Console.WriteLine($"Inner exception: {ex.InnerException.Message}");
                }

                TempData["ErrorMessage"] = $"Error creating order: {ex.Message}";

                // Reload products for the view
                var products = await _azureStorageService.GetProductsAsync();
                ViewBag.Products = products;
                return View(order);
            }
        }

        // NEW: Add to Cart functionality
        [HttpPost]
        public async Task<IActionResult> AddToCart(string productId, int quantity = 1)
        {
            if (HttpContext.Session.GetString("Role") != "Customer")
                return Json(new { success = false, message = "Please login as customer" });

            try
            {
                Console.WriteLine($"=== ADD TO CART REQUEST ===");
                Console.WriteLine($"ProductId: {productId}, Quantity: {quantity}");

                if (string.IsNullOrEmpty(productId))
                {
                    return Json(new { success = false, message = "Product ID is required" });
                }

                if (quantity <= 0)
                {
                    return Json(new { success = false, message = "Quantity must be at least 1" });
                }

                var product = await _azureStorageService.GetProductByIdAsync(productId);
                if (product == null)
                {
                    return Json(new { success = false, message = "Product not found" });
                }

                if (product.StockAvailable < quantity)
                {
                    return Json(new { success = false, message = $"Only {product.StockAvailable} items available" });
                }

                // Get current cart from session
                var cart = HttpContext.Session.Get<List<CartItem>>("ShoppingCart") ?? new List<CartItem>();

                // Check if product already in cart
                var existingItem = cart.FirstOrDefault(item => item.ProductId == productId);
                if (existingItem != null)
                {
                    existingItem.Quantity += quantity;
                }
                else
                {
                    cart.Add(new CartItem
                    {
                        ProductId = productId,
                        ProductName = product.ProductName,
                        Price = product.Price,
                        Quantity = quantity,
                        ImageUrl = product.ImageUrl
                    });
                }

                // Save cart back to session
                HttpContext.Session.Set("ShoppingCart", cart);

                Console.WriteLine($"Product added to cart. Cart now has {cart.Count} items");
                return Json(new { success = true, message = "Product added to cart", cartCount = cart.Count });
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Add to cart error: {ex.Message}");
                return Json(new { success = false, message = $"Error: {ex.Message}" });
            }
        }

        // NEW: View Cart
        public IActionResult Cart()
        {
            if (HttpContext.Session.GetString("Role") != "Customer")
                return RedirectToAction("Login", "Account");

            var cart = HttpContext.Session.Get<List<CartItem>>("ShoppingCart") ?? new List<CartItem>();
            return View(cart);
        }

        // NEW: Remove from Cart
        [HttpPost]
        public IActionResult RemoveFromCart(string productId)
        {
            if (HttpContext.Session.GetString("Role") != "Customer")
                return Json(new { success = false, message = "Please login" });

            var cart = HttpContext.Session.Get<List<CartItem>>("ShoppingCart") ?? new List<CartItem>();
            var itemToRemove = cart.FirstOrDefault(item => item.ProductId == productId);

            if (itemToRemove != null)
            {
                cart.Remove(itemToRemove);
                HttpContext.Session.Set("ShoppingCart", cart);
            }

            return Json(new { success = true, cartCount = cart.Count });
        }

        // NEW: Checkout from Cart
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(string shippingAddress)
        {
            if (HttpContext.Session.GetString("Role") != "Customer")
                return RedirectToAction("Login", "Account");

            try
            {
                Console.WriteLine("=== CHECKOUT PROCESS STARTED ===");
                var cart = HttpContext.Session.Get<List<CartItem>>("ShoppingCart") ?? new List<CartItem>();

                if (!cart.Any())
                {
                    TempData["ErrorMessage"] = "Your cart is empty";
                    return RedirectToAction("Cart");
                }

                if (string.IsNullOrEmpty(shippingAddress))
                {
                    TempData["ErrorMessage"] = "Shipping address is required";
                    return RedirectToAction("Cart");
                }

                var customerId = HttpContext.Session.GetString("UserId");
                decimal totalAmount = 0;
                var orderIds = new List<string>();

                // Create orders for each cart item
                foreach (var item in cart)
                {
                    var product = await _azureStorageService.GetProductByIdAsync(item.ProductId);
                    if (product == null)
                    {
                        TempData["ErrorMessage"] = $"Product {item.ProductName} no longer available";
                        return RedirectToAction("Cart");
                    }

                    if (product.StockAvailable < item.Quantity)
                    {
                        TempData["ErrorMessage"] = $"Only {product.StockAvailable} items of {item.ProductName} available";
                        return RedirectToAction("Cart");
                    }

                    var order = new Order
                    {
                        CustomerId = customerId,
                        ProductId = item.ProductId,
                        Quantity = item.Quantity,
                        ShippingAddress = shippingAddress,
                        Status = "Pending",
                        OrderDate = DateTime.Now,
                        TotalAmount = (decimal)(item.Price * item.Quantity)
                    };

                    await _azureStorageService.AddOrderAsync(order);

                    // Update product stock
                    product.StockAvailable -= item.Quantity;
                    await _azureStorageService.UpdateProductAsync(product, null);

                    totalAmount += order.TotalAmount;
                    orderIds.Add(order.Id);
                }

                // Clear cart
                HttpContext.Session.Remove("ShoppingCart");

                TempData["SuccessMessage"] = $"Checkout successful! {cart.Count} orders placed. Total amount: ${totalAmount}";
                Console.WriteLine("=== CHECKOUT COMPLETED SUCCESSFULLY ===");
                return RedirectToAction("MyOrders", "Customer");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Checkout error: {ex.Message}");
                TempData["ErrorMessage"] = $"Checkout failed: {ex.Message}";
                return RedirectToAction("Cart");
            }
        }

        // ========== ADMIN ORDER MANAGEMENT METHODS ==========

        // NEW: Approve Order (Admin only)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Approve(string id)
        {
            if (HttpContext.Session.GetString("Role") != "Admin")
                return RedirectToAction("Login", "Account");

            try
            {
                Console.WriteLine($"=== APPROVING ORDER {id} ===");

                var order = await _azureStorageService.GetOrderByIdAsync(id);
                if (order == null)
                {
                    TempData["ErrorMessage"] = "Order not found";
                    return RedirectToAction(nameof(Index));
                }

                order.Status = "Approved";
                await _azureStorageService.UpdateOrderAsync(order);

                Console.WriteLine($"Order {id} approved successfully");
                TempData["SuccessMessage"] = $"Order {id} has been approved successfully!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error approving order: {ex.Message}");
                TempData["ErrorMessage"] = $"Error approving order: {ex.Message}";
                return RedirectToAction(nameof(Index));
            }
        }

        // NEW: Decline Order (Admin only)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Decline(string id)
        {
            if (HttpContext.Session.GetString("Role") != "Admin")
                return RedirectToAction("Login", "Account");

            try
            {
                Console.WriteLine($"=== DECLINING ORDER {id} ===");

                var order = await _azureStorageService.GetOrderByIdAsync(id);
                if (order == null)
                {
                    TempData["ErrorMessage"] = "Order not found";
                    return RedirectToAction(nameof(Index));
                }

                order.Status = "Declined";
                await _azureStorageService.UpdateOrderAsync(order);

                Console.WriteLine($"Order {id} declined successfully");
                TempData["SuccessMessage"] = $"Order {id} has been declined.";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error declining order: {ex.Message}");
                TempData["ErrorMessage"] = $"Error declining order: {ex.Message}";
                return RedirectToAction(nameof(Index));
            }
        }

        // NEW: Update Order Status (Admin only)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateStatus(string id, string status)
        {
            if (HttpContext.Session.GetString("Role") != "Admin")
                return RedirectToAction("Login", "Account");

            try
            {
                Console.WriteLine($"=== UPDATING ORDER STATUS: {id} to {status} ===");

                var order = await _azureStorageService.GetOrderByIdAsync(id);
                if (order == null)
                {
                    TempData["ErrorMessage"] = "Order not found";
                    return RedirectToAction(nameof(Index));
                }

                order.Status = status;
                await _azureStorageService.UpdateOrderAsync(order);

                Console.WriteLine($"Order {id} status updated to {status}");
                TempData["SuccessMessage"] = $"Order status updated to: {status}";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error updating order status: {ex.Message}");
                TempData["ErrorMessage"] = $"Error updating order status: {ex.Message}";
                return RedirectToAction(nameof(Index));
            }
        }

        // NEW: Complete Order (Admin only)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Complete(string id)
        {
            if (HttpContext.Session.GetString("Role") != "Admin")
                return RedirectToAction("Login", "Account");

            try
            {
                Console.WriteLine($"=== COMPLETING ORDER {id} ===");

                var order = await _azureStorageService.GetOrderByIdAsync(id);
                if (order == null)
                {
                    TempData["ErrorMessage"] = "Order not found";
                    return RedirectToAction(nameof(Index));
                }

                order.Status = "Completed";
                await _azureStorageService.UpdateOrderAsync(order);

                Console.WriteLine($"Order {id} marked as completed");
                TempData["SuccessMessage"] = $"Order {id} has been marked as completed!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error completing order: {ex.Message}");
                TempData["ErrorMessage"] = $"Error completing order: {ex.Message}";
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: /Order/Edit/{id} (Admin only - update order status)
        public async Task<IActionResult> Edit(string id)
        {
            if (HttpContext.Session.GetString("Role") != "Admin")
                return RedirectToAction("Login", "Account");

            if (string.IsNullOrEmpty(id))
            {
                TempData["ErrorMessage"] = "Order ID is required";
                return RedirectToAction(nameof(Index));
            }

            try
            {
                var order = await _azureStorageService.GetOrderByIdAsync(id);
                if (order == null)
                {
                    TempData["ErrorMessage"] = "Order not found";
                    return RedirectToAction(nameof(Index));
                }
                return View(order);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error loading order: {ex.Message}";
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: /Order/Edit/{id} (Admin only - update order status) - FIXED VERSION
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Order order)
        {
            if (HttpContext.Session.GetString("Role") != "Admin")
                return RedirectToAction("Login", "Account");

            try
            {
                Console.WriteLine($"=== EDITING ORDER {id} ===");

                // Remove ModelState errors for fields that shouldn't be validated from form
                ModelState.Remove("CustomerId");
                ModelState.Remove("ProductId");
                ModelState.Remove("Quantity");
                ModelState.Remove("OrderDate");
                ModelState.Remove("TotalAmount");

                if (ModelState.IsValid)
                {
                    Console.WriteLine("ModelState is valid - updating order");

                    // Get the existing order to preserve other fields
                    var existingOrder = await _azureStorageService.GetOrderByIdAsync(id);
                    if (existingOrder == null)
                    {
                        TempData["ErrorMessage"] = "Order not found";
                        return RedirectToAction(nameof(Index));
                    }

                    // Update only the fields that should be editable
                    existingOrder.Status = order.Status;
                    existingOrder.ShippingAddress = order.ShippingAddress;

                    Console.WriteLine($"Updating order - Status: {existingOrder.Status}, Shipping: {existingOrder.ShippingAddress}");

                    await _azureStorageService.UpdateOrderAsync(existingOrder);

                    TempData["SuccessMessage"] = $"Order updated successfully! Status: {order.Status}";
                    Console.WriteLine("=== ORDER UPDATED SUCCESSFULLY ===");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    Console.WriteLine("ModelState is INVALID");
                    foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                    {
                        Console.WriteLine($"Validation error: {error.ErrorMessage}");
                    }
                    return View(order);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"=== ORDER UPDATE FAILED ===");
                Console.WriteLine($"Error: {ex.Message}");
                Console.WriteLine($"Stack trace: {ex.StackTrace}");

                TempData["ErrorMessage"] = $"Error updating order: {ex.Message}";
                return View(order);
            }
        }

        // POST: /Order/Delete/{id} (Admin only)
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (HttpContext.Session.GetString("Role") != "Admin")
                return RedirectToAction("Login", "Account");

            try
            {
                Console.WriteLine($"=== DELETING ORDER {id} ===");

                await _azureStorageService.DeleteOrderAsync(id);

                Console.WriteLine($"Order {id} deleted successfully");
                TempData["SuccessMessage"] = $"Order deleted successfully.";
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error deleting order: {ex.Message}");
                TempData["ErrorMessage"] = $"Error deleting order: {ex.Message}";
            }
            return RedirectToAction(nameof(Index));
        }

        // NEW: Bulk Actions for Admin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BulkApprove(string[] orderIds)
        {
            if (HttpContext.Session.GetString("Role") != "Admin")
                return RedirectToAction("Login", "Account");

            try
            {
                if (orderIds == null || !orderIds.Any())
                {
                    TempData["ErrorMessage"] = "No orders selected";
                    return RedirectToAction(nameof(Index));
                }

                int successCount = 0;
                foreach (var orderId in orderIds)
                {
                    try
                    {
                        var order = await _azureStorageService.GetOrderByIdAsync(orderId);
                        if (order != null && order.Status == "Pending")
                        {
                            order.Status = "Approved";
                            await _azureStorageService.UpdateOrderAsync(order);
                            successCount++;
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error approving order {orderId}: {ex.Message}");
                    }
                }

                TempData["SuccessMessage"] = $"{successCount} orders approved successfully!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error bulk approving orders: {ex.Message}";
                return RedirectToAction(nameof(Index));
            }
        }
    }
}